// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package members

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "lms/internal/models"

func StaffSearch(staff []models.Staff) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><h1>Staff Search</h1><a href=\"/staff/add\">Add Staff</a><form method=\"GET\" action=\"/staff/search\"><input type=\"text\" name=\"fullName\" placeholder=\"name\"> <input type=\"text\" name=\"username\" placeholder=\"national id\"> <input type=\"text\" name=\"email\" placeholder=\"email\"> <select name=\"role\" aria-label=\"Select sole\"><option selected disabled value=\"\">Select role</option> <option value=\"librarian\">Librarian</option> <option value=\"admin\">Admin</option></select> <select name=\"status\" aria-label=\"Select status\"><option selected disabled value=\"\">Select status</option> <option value=\"active\">Active</option> <option value=\"suspended\">Suspended</option></select> <button type=\"submit\">Search</button></form><div id=\"results\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = StaffList(staff).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
