// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package books

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoanAddForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><form hx-post=\"/loans/add\" hx-target=\"#results\" hx-swap=\"innerHTML\"><div><label for=\"bookId\">Book Id:</label> <input id=\"bookId\" type=\"number\" name=\"bookId\" required></div><div><label for=\"memberId\">Member Id:</label> <input id=\"memberId\" type=\"number\" name=\"memberId\" required></div><div><label for=\"dueDate\">Due Date:</label> <input id=\"dueDate\" type=\"date\" name=\"dueDate\" required></div><div><label for=\"borrowDate\">Borrow Date:</label> <input type=\"date\" id=\"borrowDate\" name=\"borrowDate\" required></div><button type=\"submit\">Add Loan</button></form><div id=\"results\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
